[package]
name = "lapce"
version = "0.2.8"
authors = ["Dongdong Zhou <dzhou121@gmail.com>"]
edition = "2021"
default-run = "lapce"

[dependencies]
lapce-ui = { path = "./lapce-ui" }
lapce-proxy = { path = "./lapce-proxy" }
crossbeam-channel = "0.5.0"

[[bin]]
name = "lapce"
path = "lapce-ui/src/bin/lapce.rs"

[workspace]
members = ["lapce-ui", "lapce-proxy", "lapce-rpc", "lapce-data", "lapce-core"]

[workspace.package]
version = "0.2.8"
edition = "2021"
rust-version = "1.64"
homepage = "https://lapce.dev"
authors = ["Dongdong Zhou <dzhou121@gmail.com>"]

[workspace.dependencies]
alacritty_terminal = "0.17.0"
anyhow = "1.0"
chrono = "0.4"
clap = { version = "3.2.17", features = ["derive"] }
crossbeam-channel = "0.5.0"
directories = "4.0.1"
flate2 = "1.0"
hashbrown = { version = "0.12.3", features = ["serde"] }
im = { version = "15.0.0", features = ["serde"] }
include_dir = "0.6.2"
indexmap = { version = "1.9", features = ["serde"] }
interprocess = "1.1.1"
itertools = "0.10.1"
log = "0.4"
notify = { version = "5.0.0", features = ["serde"] }
once_cell = "1.17"
rayon = "1.5.1"
regex = "1.7.0"
reqwest = { version = "0.11", features = ["blocking", "json", "socks"] }
serde = "1.0"
serde_json = "1.0"
smallvec = "1.10.0"
strum = "0.21.0" # follow same version as system-deps in lockfile
strum_macros = "0.21.1" # ditto
tar = "0.4"
thiserror = "1.0"
toml_edit = { version = "0.14.4", features = ["easy"] }
swash = { path = "../swash", version = "0.1.6" }

psp-types = { path = "../psp-types" }


lapce-xi-rope = { version = "0.3.1", features = ["serde"] }

lapce-core = { path = "./lapce-core" }
lapce-rpc = { path = "./lapce-rpc" }
lapce-data = { path = "./lapce-data" }
lapce-proxy = { path = "./lapce-proxy" }

[workspace.dependencies.druid]
# git = "https://github.com/lapce/druid"
# branch = "shell_opengl"
path = "../druid/druid"
features = ["svg", "im", "serde"]
